[package]
name = "iomust_signaling_server"
version = "0.1.0"
edition = "2018"

[dependencies]
env_logger = "0.9"
iomust_signaling_messages = { path = "../iomust_signaling_messages" }
log = "0.4"
serde = "1.0"
serde_json = "1.0"
