[package]
name = "iomust_server"
version = "0.1.0"
edition = "2018"

[dependencies]
env_logger = "0.9"
iomust_messages = { path = "../iomust_messages" }
log = "0.4"
rand = "0.8"
serde_json = "1.0"
tokio = { version = "1.12", features = ["io-util", "macros", "net", "rt-multi-thread", "sync"] }
